language: python

python:
  - 2.7

cache:
  pip: true
  directories:
    - buildout-cache/downloads
    - buildout-cache/eggs

env:
  - PLONE_VERSION=4
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1

install:
  - sudo apt-get -qq install libfreetype6-dev liblcms1-dev libreoffice
  - mkdir -p buildout-cache/{eggs,downloads}
  - mkdir $HOME/tmp
  - chmod 777 $HOME/tmp
  - export TMPDIR=$HOME/tmp
  - sed -ie "s#plone-5#plone-$PLONE_VERSION#" buildout.cfg
  - sed -ie "s#travis-5#travis-$PLONE_VERSION#" travis.cfg
  - virtualenv-2.7 .
  - ./bin/python bootstrap.py
  - bin/buildout -N -c travis.cfg annotate
  - bin/buildout -N -c travis.cfg
  - sed -ie "s#'/usr/bin/python3'#'/usr/bin/python'#" bin/test
  - bin/translation-manage -c

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo soffice --invisible --headless --nofirststartwizard --nologo "--accept=socket,host=localhost,port=2002;urp;" &
#  - /usr/bin/python -c "import uno;context=uno.getComponentContext();resolver=context.ServiceManager.createInstanceWithContext('com.sun.star.bridge.UnoUrlResolver',context);docContext=resolver.resolve('uno:socket,host=localhost,port=2002;urp;StarOffice.ComponentContext');print(docContext)"

script:
  - bin/test

after_success:
  - bin/createcoverage
  - pip install --upgrade pip
  - pip install -q coveralls==0.5
  - coveralls

notifications:
  email:
    recipients:
      - devs@imio.be
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
