os:
  - linux
dist: bionic
language: python

cache:
  pip: true
  directories:
    - eggs
    - buildout-cache/downloads
    - buildout-cache/eggs
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2

jobs:
  fast_finish: true

services:
  - docker

before_install:
  - pip install --upgrade pip
  - docker pull xcgd/libreoffice:latest

install:
  - sudo apt update -qq -y
  - sudo apt-get install -qq -y libfreetype6-dev liblcms2-dev make libreoffice libreoffice-script-provider-python
  - sudo apt-get autoremove -qq -y
  - sudo apt-get autoclean -qq -y
  - mkdir -p buildout-cache/{eggs,downloads}
  - mkdir $HOME/tmp
  - chmod 777 $HOME/tmp
  - export TMPDIR=$HOME/tmp
  - sed -ie "s#plone-5#plone-$PLONE_VERSION#" travis.cfg
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - python -V
  - /usr/bin/python3 -V
  - bin/buildout -N -c travis.cfg annotate
  - bin/buildout -Nt 5 -c travis.cfg

before_script:
  - bin/translation-manage -c
  - make startlibreoffice

script:
  - bin/code-analysis
  - bin/test

after_success:
  - make stoplibreoffice
  - bin/coverage run bin/test --test=\!"robot"
  - pip install coverage==4.5.4
  - python -m coverage.pickle2json
  - pip install coveralls
  - coveralls

notifications:
  email:
    recipients:
      - devs@imio.be
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
